---
# yamllint disable rule:line-length rule:truthy

name: Pipeline CI
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches: main

jobs:
  git-version-gating:
    uses: OpsInc/workflow-lib/.github/workflows/git-version-gating.yml@main

  terraform-CI:
    uses: OpsInc/workflow-lib/.github/workflows/terraform-CI.yml@feature/add-terraform
    with:
      ENVIRONMENT: "sbx"
      TFVARS_PATH: "vars"
    secrets: inherit
